gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the Hoenn Region!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me --\p"
	.string "$"

@unused (see: gText_ThisIsAPokemon)
gText_Birch_Pokemon::
	.string "Huh?”\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Heeey, you must be the new kid.\p"
	.string "Birch: Oh, hello, Gulpinator.\p"
	.string "Gulpinator: That's right!\n"
	.string "I'm a Gulpin. We're the best!\p"
	.string "There's no problem we can't gulp down!\p"
	.string "But anyway, welcome to Littleroot.\n"
	.string "It's alright.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Birch: Soooo, moving on.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\n"
	.string "You're {PLAYER}{KUN}, I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Hoenn where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Lab.\p"
	.string "...\p"
	.string "Gulpinator: Taste you later!\p"
	.string "$"
